
language: android
android:
  components:
    - platform-tools
    - tools

    - build-tools-23.0.2

    - android-17

before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk
  - export ANDROID_NDK_HOME=$HOME/android-ndk

script:
  - $ANDROID_NDK_HOME/ndk-build
  - ant release
